feat: added exports to get accounts
esx-framework/esx_addonaccount pull request #12
Opened 2024-07-26 19:08 UTC by Mirrrrrow

Added two exports to get the accounts.
See usage in the README file.

Suggestion: #11

2024-07-27 13:44 UTC, Gellipapa requested changes

2024-07-27 13:44 UTC, Gellipapa commented on server/main.lua
> +exports('getAccount', GetSharedAccount)
I think this is a typo, getAccount should be called here.

2024-07-27 15:13 UTC, Mirrrrrow commented on server/main.lua
> +exports('getAccount', GetSharedAccount)
Yes, I'll change it when I'm at home

2024-07-28 16:25 UTC, Mirrrrrow commented
@Gellipapa fixed it

2024-07-29 16:21 UTC, Gellipapa approved these changes

2024-07-29 16:21 UTC, merged