exports update and fxmanifest vers
esx-framework/esx_addonaccount pull request #13
Opened 2024-07-29 22:17 UTC by t1ger-scripts

Export for shared account already existed in fxmanifest.lua, so removed from server/main.lua.
Alongside the other exports, I added GetAccount and removed it from the server file as well. 

Also figured to update the script version, as it hasn't been done in ages.

2024-07-30 13:52 UTC, Mirrrrrow commented
In my opinion exports should always be put in the file itself (here: server.lua).
It is the same for the getSharedObject export and FiveM themself say that instead of using fxmanifest, we should try using the function itself.

2024-07-31 17:54 UTC, Gellipapa commented
@t1ger-scripts  Hi! Yes as @Mirrrrrow says don't use this old system it is much more visible, searchable, debuggable if you put it directly in the file than in fxmanifest. 

Please modify this so that everything is exported in that file.

Then I can merge it.

2024-07-31 17:55 UTC, Gellipapa requested changes
Add to exports to file, and remove in fxmanifest.

2024-09-15 13:12 UTC, Gellipapa approved these changes
It's good because that's the way exports used to be.

2024-09-15 13:12 UTC, merged