feat(function/exports): AddSharedAccount(society, amount)
esx-framework/esx_addonaccount pull request #3
Opened 2023-03-20 21:55 UTC by wasabirobby

Gives the ability to create shared accounts during runtime as well as exports to integrate with 3rd party addons

2023-03-20 22:02 UTC, Gellipapa reviewed
Please handle nil values.

2023-03-20 22:22 UTC, Thekuca requested changes
please change to oxmysql funcs and don't use named placeholders (slower) for sql tasks

2023-06-15 23:44 UTC, Gellipapa commented
@wasabirobby Hi! Do you can fix request changes and resolved merge conflict? Please.

2023-06-17 05:49 UTC, wasabirobby reviewed
I hope recent commit solves comments

2023-06-17 05:51 UTC, wasabirobby commented on server/main.lua
> +function AddSharedAccount(society, amount)
Done :)

2023-06-17 12:11 UTC, Gellipapa approved these changes

2023-06-17 12:12 UTC, Gellipapa commented
@wasabirobby Thank you fixes.

2023-06-17 12:12 UTC, merged